In [ ]:
#Question 3.1

masses = [1.9891e+30, 1.8986e+27, 
          5.6846e+26, 1.0243e+26, 8.6810e+25,
          5.9736e+24, 4.8685e+24, 6.4185e+23, 
          3.3022e+23, 7.349e+22, 1.25e22]

a = 7.349e+22

b = []
for i in masses:
    while i > a:
        b.append(i)
        
print(b)
        
b_slice = b[slice(0, 5, 1)]
print(b_slice)

d = sum(b_slice)/(len(b_slice))


In [25]:
#Question 3.2

import math as m
from scipy.constants import G

masses = [1.9891e+30, 1.8986e+27, 5.6846e+26, 
          1.0243e+26, 8.6810e+25, 5.9736e+24, 
          4.8685e+24, 6.4185e+23, 3.3022e+23, 
          7.349e+22, 1.25e22]
radii  = [696340, 71492, 60268, 24764, 
          25559, 6378.1, 6051.8, 3396.2, 
          2439.7, 1738.1, 1195]
names  = ['Sun', 'Jupiter', 'Saturn', 'Neptune', 
          'Uranus', 'Earth', 'Venus', 'Mars', 
          'Mercury', 'Moon', 'Pluto']

c = []
for i in range (len(names)):
    print(f"{masses[i]:.3} is the mass of {names[i]}")
    d = m.sqrt((2*G*masses[i])/(radii[i]))
    c.append(d)

print(c)

esc_v = dict(zip(names, c))
print(esc_v)

1.99e+30 is the mass of Sun
1.9e+27 is the mass of Jupiter
5.68e+26 is the mass of Saturn
1.02e+26 is the mass of Neptune
8.68e+25 is the mass of Uranus
5.97e+24 is the mass of Earth
4.87e+24 is the mass of Venus
6.42e+23 is the mass of Mars
3.3e+23 is the mass of Mercury
7.35e+22 is the mass of Moon
1.25e+22 is the mass of Pluto
[19526998.674313523, 1882807.3047839785, 1122081.5596980709, 743055.1496485014, 673334.4094035377, 353582.0966705394, 327697.5265269787, 158831.99966116823, 134416.11319577054, 75126.75034537194, 37367.058636313704]
{'Sun': 19526998.674313523, 'Jupiter': 1882807.3047839785, 'Saturn': 1122081.5596980709, 'Neptune': 743055.1496485014, 'Uranus': 673334.4094035377, 'Earth': 353582.0966705394, 'Venus': 327697.5265269787, 'Mars': 158831.99966116823, 'Mercury': 134416.11319577054, 'Moon': 75126.75034537194, 'Pluto': 37367.058636313704}


In [6]:
#Question 3.5

for i in range (100000):
    i = i + 1
    a = 1/(i**2)

print(a)


#doesnt converge


1e-10


In [28]:
#Question 3.7

import math as m


def size(d,D):
    c = (2*m.atan((d)/(2*D)))*(180/m.pi)
    print(c)
    
d = float(input("size of the object?"))
D = float(input("Distance of the object?"))

size(d,D)



size of the object? 1
Distance of the object? 2


28.072486935852957


In [40]:
#Questiopn 3.10

import math as m

def av(r):
    A = 2*m.pi*r**2 + 2*m.pi*r*h
    V = m.pi*r**2*h
    return A,V


r = float(input("radius?"))
h = float(input('height?'))

A, V = av(r)
print(f"{A} is the area")
print(f"{V} is the volume")
print(f"{A/V} is the ratio of the area to the volume")

radius? 2
height? 3


62.83185307179586 is the area
37.69911184307752 is the volume
1.6666666666666667 is the ratio of the area to the volume


In [67]:
#question 3.14

import numpy as np
a = [1, 10**2, 2*10, 5.1*20, -4, 4.45*22]

print(np.array(a))

y = np.linspace(1, 2.5, 20)
print(y)

z = np.arange(1, 2.6, 0.1)
print(z)

x = np.random.normal(loc=0.0, scale=5, size=10000)
print(x)
a = np.where(x>5)
print(a)

c = 




[  1.  100.   20.  102.   -4.   97.9]
[1.         1.07894737 1.15789474 1.23684211 1.31578947 1.39473684
 1.47368421 1.55263158 1.63157895 1.71052632 1.78947368 1.86842105
 1.94736842 2.02631579 2.10526316 2.18421053 2.26315789 2.34210526
 2.42105263 2.5       ]
[1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.8 1.9 2.  2.1 2.2 2.3 2.4 2.5]
[ 0.97410892  0.95456374 -3.03826964 ... -7.43671746 -6.06052522
  0.916871  ]
(array([   7,    9,   11, ..., 9976, 9990, 9995]),)
